### ISSUE TITLE
[Expected?] Does not remember its window size

### ISSUE THREAD

**Issue by Sky-NiniKo** [nate-xyz/resonance#12]
I know that the window on the first startup is not supposed to be resized so I don't know if it's intended to be but when reopening the application, it still takes up all the available space even though it was resized small when closed.

I'm not too bothered that the application forces a certain size when it first opens even if I think it's annoying for people using a tiling window manager.
However, I'm against forcing a size on every startup - especially for it to be so big - and that's why I think the application should remember its size on closing.

_PS: After rereading, I realized that some of the sentences were a bit confusing and I apologize for this. It mean that you can ask if you don't understood something because it's my fault_

**Comment by nate-xyz** [comment]
I'm not sure if remembering window size on close is something I can easily do with gtk, but I could add a setting to change the default window size. Would that address your issue?

**Comment by tfuxu** [comment]
Tutorials on GNOME's developer documentation use for some reason `Gio.Settings.bind()` function, which can lead to lags because of blocking disk I/O activity. This is how it was addressed in Gradience: https://github.com/GradienceTeam/Gradience/pull/446. 

As a note, Resonance doesn't support fullscreen mode, so `window-fullscreen` key from that PR won't be needed, and `window-height` and `window-width` keys can be connected into one key accepting values in array ("as" type in gschema syntax).

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/resonance/commit/c78518a877d3ab59cb942d1dfab163b413a78081
